language: node_js
dist: trusty
sudo: required
node_js: 8
cache:
  directories:
  - node_modules
env:
  global:
  - BX_APP=discovery-news-demo
  - BX_API=https://api.ng.bluemix.net
  - BX_ORGANIZATION=WatsonPlatformServices
  - BX_SPACE=demos
script:
- npm run test
- npm run build
before_deploy: npm install -g bx-blue-green
deploy:
- provider: script
  skip_cleanup: true
  script:
  - bx-blue-green-travis
  on:
    branch: master
    repo: watson-developer-cloud/discovery-nodejs
- provider: script
  skip_cleanup: true
  script: npx semantic-release
  on:
    node: 8