language: node_js
dist: trusty
sudo: required
node_js: 8
before_install:
- openssl aes-256-cbc -K $encrypted_aba75b5b520c_key -iv $encrypted_aba75b5b520c_iv
  -in .env.enc -out .env -d
script:
  - ./.travis_script.sh
cache:
  directories:
  - node_modules
deploy:
- provider: script
  skip_cleanup: true
  script: npx semantic-release
  on:
    node: 8